root = "."

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
exclude_regex = ["_test.go"]
log = "build-errors.log"
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
